version: '3'

services:
  api:
    container_name: node_nginx
    build: ./api
    command: npm run dev
    restart: unless-stopped
    volumes:
      - ./api/src:/usr/src/app/src
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=http://realworld.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
    networks:
      - node_network

  api_db:
    container_name: node_db
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - node_network

networks:
  node_network:
    driver: bridge
